# Streamlit Cloud Secrets Configuration
# Copy these to your Streamlit Cloud App Settings > Secrets

# Supabase Project Details
SUPABASE_URL = "https://mvnvxfuiyggatlakgrbr.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12bnZ4ZnVpeWdnYXRsYWtncmJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2ODkzNzMsImV4cCI6MjA3NTI2NTM3M30.n87xIgUbXcVrtGq7JkEYy1LvBHiXoXnLCJW5y8s1mGo"

# Supabase Database Connection (Direct)
SUPABASE_HOST = "db.mvnvxfuiyggatlakgrbr.supabase.co"
SUPABASE_PORT = "5432"
SUPABASE_USER = "postgres"
SUPABASE_PASSWORD = "MeetEase@4545"
SUPABASE_DATABASE = "postgres"

# OpenAI API Key (replace with your actual key)
OPENAI_API_KEY = "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"

# Optional: Model Configuration
MEETEASE_EMBED_MODE = "minilm"
MEETEASE_MINILM = "sentence-transformers/all-MiniLM-L6-v2"
MEETEASE_WHISPER_MODEL = "base"
MEETEASE_TEMPERATURE = "0.2"
MEETEASE_MAX_INPUT_TOKENS = "3000"
