# .streamlit/secrets.toml
[postgres]
host = "db.mhgbdxadbvrmeffljnry.supabase.co"   # use DB host shown in Supabase -> Settings -> Database -> Connection string
port = "6543"                                 # or 5432 if you prefer direct
database = "postgres"
user = "postgres"
password = "REPLACE_WITH_DB_PASSWORD"

[supabase]
url = "https://mhgbdxadbvrmeffljnry.supabase.co"
anon_key = "REPLACE_WITH_YOUR_ANON_KEY"         # safe for client-like operations (limited access)
service_role_key = "REPLACE_WITH_SERVICE_ROLE"  # use only on server-side and keep secret
