PGHOST = "db.mvnvxfuiyggatlakgrbr.supabase.co"
PGPORT = "5432"                # if this fails, code auto-tries pooler 6543
PGDATABASE = "postgres"
PGUSER = "postgres"
PGPASSWORD = "MeetEase@4545"
PGSSLMODE = "require"

# Optional: if Supabase shows a specific Pooler host, set it:
# PGHOST_POOLER = "YOUR_POOLER_HOST"  # often the same host, sometimes distinct
PGPORT_POOLER = "6543"
